export enum Authority {
  ADMIN = 'ROLE_ADMIN',
  USER = 'ROLE_USER',
  MANAGER = 'ROLE_MANAGER',
  ACTIVATE_AFFAIRE = 'ROLE_ACTIVATE_AFFAIRE',
  CAN_ACTIVATE_BON_COMMANDE = 'ROLE_CAN_ACTIVATE_BON_COMMANDE',
  CAN_ACTIVATE_OT_EXTERNE = 'ROLE_CAN_ACTIVATE_OT_EXTERNE',
  CAN_SEE_PRICE = 'ROLE_CAN_SEE_PRICE',
}
